# Generated by Django 3.2.5 on 2021-07-14 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='numero_de_chapa',
            field=models.IntegerField(blank=True),
        ),
    ]
