# Generated by Django 3.2.5 on 2021-07-14 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_numero_de_chapa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='numero_de_chapa',
            field=models.IntegerField(db_index=True, unique=True),
        ),
    ]
