# Generated by Django 3.2.5 on 2021-07-14 23:04

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ocorrencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateTimeField(auto_now=True)),
                ('categorias', models.CharField(choices=[('descarte', 'Descarte irregular de residuos'), ('desmatamento', 'Desmatamento'), ('loteamento_irregular', 'Loteamento irregular'), ('uso_area_publica', 'Uso indevido de área pública'), ('maltrato_animais', 'Maltrato de animais'), ('abandono_animais', 'Abandono de animais')], max_length=255)),
                ('andamento', models.CharField(blank=True, choices=[('descarte', 'Registro do auto de infração - AI'), ('desmatamento', 'Encaminhamento do AI à 2ª. Promotoria de Justiça'), ('loteamento_irregular', 'Encaminhamento do AI à 7ª. Promotoria de Justiça'), ('uso_area_publica', 'Encaminhamento do AI à Polícia Civil'), ('maltrato_animais', 'Encaminhamento do AI à Polícia Militar Ambiental'), ('abandono_animais', 'Encaminhamento do AI à CETESB')], max_length=255)),
                ('localizacao', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('nome_logradouro', models.CharField(max_length=240)),
                ('numero', models.CharField(blank=True, max_length=240)),
                ('bairro', models.CharField(max_length=240)),
                ('descricao', models.CharField(max_length=240)),
                ('ponto_referencia', models.CharField(blank=True, max_length=240)),
                ('observacoes', models.CharField(blank=True, max_length=240)),
                ('infrator_identificado', models.BooleanField(blank=True)),
                ('loteamento_area', models.CharField(blank=True, max_length=240)),
                ('loteamento_proprietario', models.CharField(blank=True, max_length=240)),
                ('loteamento_contato', models.CharField(blank=True, max_length=240)),
                ('numero_auto', models.CharField(blank=True, max_length=240)),
                ('imagem', models.ImageField(max_length=254, upload_to='media/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
    ]
