# Generated by Django 3.2.5 on 2021-07-14 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscalizaMapa', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ocorrencia',
            old_name='imagem',
            new_name='imagem_1',
        ),
        migrations.AddField(
            model_name='ocorrencia',
            name='imagem_2',
            field=models.ImageField(blank=True, max_length=254, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='ocorrencia',
            name='imagem_3',
            field=models.ImageField(blank=True, max_length=254, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='ocorrencia',
            name='imagem_4',
            field=models.ImageField(blank=True, max_length=254, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='ocorrencia',
            name='imagem_5',
            field=models.ImageField(blank=True, max_length=254, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='ocorrencia',
            name='imagem_6',
            field=models.ImageField(blank=True, max_length=254, upload_to='media/'),
        ),
    ]
