# Generated by Django 3.2.5 on 2021-07-15 22:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fiscalizaMapa', '0002_auto_20210714_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocorrencia',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
